<template>
  <el-container :style="constyle" class="list-container" v-loading="fromDataLoading">
    <el-header class="list-header">
      <div style="padding: 0px">
        <span>{{form.orgName}}</span>
        <div style="float: right">
          <el-button size="mini" type="primary" @click="butSubmitClick" plain icon="el-icon-edit" >保存</el-button>
        </div>
      </div>
    </el-header>
    <el-main class="list-main">
      <el-form :model="form" :rules="rules" ref="elForm" size="mini" label-width="100px" class="elform">
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构名称" prop="orgName"><el-input v-model="form.orgName"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构简称" prop="orgAlias"><el-input v-model="form.orgAlias"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构类别" prop="orgClass"><el-input v-model="form.orgClass"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构缩写" prop="orgAbbr"><el-input v-model="form.orgAbbr"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构类型" prop="orgType"><cq-select v-model="form.orgType" dataurl="/BaseDict/getDict?dict_name=2"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构英文名" prop="englishName"><el-input v-model="form.englishName"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构规模" prop="orgScale"><el-input v-model="form.orgScale"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="上级机构" prop="upperOrg"><el-input v-model="form.upperOrg"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构等级" prop="orgLevel"><el-input v-model="form.orgLevel"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构行政区划" prop="zoneCode"><el-input v-model="form.zoneCode"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="邮政编码" prop="postCode"><el-input v-model="form.postCode"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="通信地址" prop="postAddress"><el-input v-model="form.postAddress"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="网站地址" prop="internetSite"><el-input v-model="form.internetSite"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="系统进场时间" prop="projectStartTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.projectStartTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构IP起始号" prop="startIpAddress"><el-input v-model="form.startIpAddress"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="门诊启用时间" prop="dispStartTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.dispStartTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构IP终止号" prop="endIpAddress"><el-input v-model="form.endIpAddress"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="住院启用时间" prop="resiStartTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.resiStartTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构授权码" prop="orgAuthorizationKey"><el-input v-model="form.orgAuthorizationKey"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="系统验收时间" prop="projectEndTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.projectEndTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="当前住院号" prop="currentResiCaseNo"><el-input v-model="form.currentResiCaseNo"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="有效标志" prop="validFlag"><el-input v-model="form.validFlag"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="自定义编码" prop="customCode"><el-input v-model="form.customCode"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="用户编码" prop="userCode"><el-input v-model="form.userCode"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="拼音首码" prop="spellCode"><el-input v-model="form.spellCode"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="修改时间" prop="modifyTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.modifyTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="五笔首码" prop="wbzxCode"><el-input v-model="form.wbzxCode"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="修改人" prop="modifyOperator"><el-input v-model="form.modifyOperator"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="排序号" prop="sortNo"><el-input v-model="form.sortNo"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="备注" prop="remark"><el-input v-model="form.remark"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="创建时间" prop="createTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.createTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="负责行政区" prop="zoneCustomCode"><el-input v-model="form.zoneCustomCode"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="创建人" prop="createOperator"><el-input v-model="form.createOperator"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="上级行政机构" prop="belongOrg"><el-input v-model="form.belongOrg"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ZONE_CUSTOM_LEVEL" prop="zoneCustomLevel"><el-input v-model="form.zoneCustomLevel"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="组织机构编码" prop="organizationCode"><el-input v-model="form.organizationCode"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="PROJECT_STATUS" prop="projectStatus"><el-input v-model="form.projectStatus"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="SESSION_ID" prop="sessionId"><el-input v-model="form.sessionId"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ALLOW_JOIN_CHAT" prop="allowJoinChat"><el-input v-model="form.allowJoinChat"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="INSUR_LOG_ID" prop="insurLogId"><el-input v-model="form.insurLogId"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="IS_DELIVERY_ORG" prop="isDeliveryOrg"><el-input v-model="form.isDeliveryOrg"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="INSUR_LOG_PASS" prop="insurLogPass"><el-input v-model="form.insurLogPass"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ORG_MEMO" prop="orgMemo"><el-input v-model="form.orgMemo"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="SESSION_CREATE_TIME" prop="sessionCreateTime"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.sessionCreateTime" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="IS_HYGIENE_ORG" prop="isHygieneOrg"><el-input v-model="form.isHygieneOrg"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="严精国家机构编码" prop="orgCountyCode"><el-input v-model="form.orgCountyCode"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="上级结防所" prop="upperJfs"><el-input v-model="form.upperJfs"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="基层机构类型" prop="orgLx"><el-input v-model="form.orgLx"/></el-form-item></el-col></el-row>
        <el-row><el-col><el-form-item label="上级精神中心" prop="upperJszx"><el-input v-model="form.upperJszx"/></el-form-item></el-col></el-row>
        <el-row><el-col><el-form-item label="行政级别社区" prop="zoneLevel"><el-input v-model="form.zoneLevel"/></el-form-item></el-col></el-row>
        <el-row><el-col><el-form-item label="行政级别精神" prop="zoneLevelJs"><el-input v-model="form.zoneLevelJs"/></el-form-item></el-col></el-row>
      </el-form>
    </el-main>
  </el-container>
</template>
<script src="./OrgDictEdit.js"></script>
<style scoped src="../../../assets/css/base-form.css"></style>
