<template>
  <el-dialog title="地址" :visible.sync="dialogFormVisible" width="80%" append-to-body>
      <el-form :model="form" :rules="rules" ref="elForm" size="mini" label-width="100px">
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="机构" prop="org_id"><el-input v-model="form.org_id" :disabled="disabledFlag.disabled_org_id" :readonly="readonlyFlag.readonly_org_id"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="USER_CODE" prop="user_code"><el-input v-model="form.user_code" :disabled="disabledFlag.disabled_user_code" :readonly="readonlyFlag.readonly_user_code"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="行政区划" prop="zone_code"><el-input v-model="form.zone_code" :disabled="disabledFlag.disabled_zone_code" :readonly="readonlyFlag.readonly_zone_code"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="CUSTOM_CODE" prop="custom_code"><el-input v-model="form.custom_code" :disabled="disabledFlag.disabled_custom_code" :readonly="readonlyFlag.readonly_custom_code"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="地址编码" prop="address_code"><el-input v-model="form.address_code" :disabled="disabledFlag.disabled_address_code" :readonly="readonlyFlag.readonly_address_code"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="SPELL_CODE" prop="spell_code"><el-input v-model="form.spell_code" :disabled="disabledFlag.disabled_spell_code" :readonly="readonlyFlag.readonly_spell_code"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="地址名称" prop="address_name"><el-input v-model="form.address_name" :disabled="disabledFlag.disabled_address_name" :readonly="readonlyFlag.readonly_address_name"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="WBZX_CODE" prop="wbzx_code"><el-input v-model="form.wbzx_code" :disabled="disabledFlag.disabled_wbzx_code" :readonly="readonlyFlag.readonly_wbzx_code"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="地址全称" prop="address_full_name"><el-input v-model="form.address_full_name" :disabled="disabledFlag.disabled_address_full_name" :readonly="readonlyFlag.readonly_address_full_name"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="排序号" prop="sort_no"><el-input v-model="form.sort_no" :disabled="disabledFlag.disabled_sort_no" :readonly="readonlyFlag.readonly_sort_no"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ADDRESS_AREA" prop="address_area"><el-input v-model="form.address_area" :disabled="disabledFlag.disabled_address_area" :readonly="readonlyFlag.readonly_address_area"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="创建时间" prop="create_time"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.create_time" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss" :disabled="disabledFlag.disabled_create_time"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ADDRESS_FLOOR" prop="address_floor"><el-input v-model="form.address_floor" :disabled="disabledFlag.disabled_address_floor" :readonly="readonlyFlag.readonly_address_floor"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="创建人" prop="create_operator"><el-input v-model="form.create_operator" :disabled="disabledFlag.disabled_create_operator" :readonly="readonlyFlag.readonly_create_operator"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="ADDRESS_NUMBER" prop="address_number"><el-input v-model="form.address_number" :disabled="disabledFlag.disabled_address_number" :readonly="readonlyFlag.readonly_address_number"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="修改时间" prop="modify_time"><div class="block"/><el-date-picker class="cq-inputdatetime" v-model="form.modify_time" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss" :disabled="disabledFlag.disabled_modify_time"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="有效标志" prop="valid_flag"><el-input v-model="form.valid_flag" :disabled="disabledFlag.disabled_valid_flag" :readonly="readonlyFlag.readonly_valid_flag"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="修改人" prop="modify_operator"><el-input v-model="form.modify_operator" :disabled="disabledFlag.disabled_modify_operator" :readonly="readonlyFlag.readonly_modify_operator"/></el-form-item></el-col></el-row>
        <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="SEL_ORG_ID" prop="sel_org_id"><el-input v-model="form.sel_org_id" :disabled="disabledFlag.disabled_sel_org_id" :readonly="readonlyFlag.readonly_sel_org_id"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="备注" prop="remark"><el-input v-model="form.remark" :disabled="disabledFlag.disabled_remark" :readonly="readonlyFlag.readonly_remark"/></el-form-item></el-col></el-row>
      </el-form>
    <div slot="footer" class="dialog-footer" >
      <el-button size="mini"  @click="dialogFormVisible = false">取 消</el-button>
      <el-button size="mini" type="primary" @click="butSubmitClick">确 定</el-button>
    </div>
  </el-dialog>
</template>
<script src="./AddressDictEdit.js"></script>
<style scoped src="../../../assets/css/base-form.css"></style>
